# Generated by Django 6.0 on 2025-12-05 16:06

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdsource', '0002_book_article_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
