# Generated by Django 6.0 on 2025-12-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdsource', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='封面图片'),
        ),
    ]
