# Generated by Django 6.0 on 2025-12-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdsource', '0005_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=False, help_text='True表示已发布，False表示未发布', verbose_name='发布状态'),
        ),
    ]
