# Generated by Django 6.0 on 2025-12-30 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdsource', '0006_book_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_USER', '创建用户'), ('UPDATE_USER', '更新用户'), ('DELETE_USER', '删除用户'), ('GRANT_PERMISSION', '授予权限'), ('REVOKE_PERMISSION', '撤销权限'), ('SYSTEM_INIT', '系统初始化'), ('ACCESS_ADMIN', '访问管理页面'), ('MODIFY_BOOK', '修改书籍'), ('MODIFY_ARTICLE', '修改文章'), ('DELETE_BOOK', '删除书籍'), ('DELETE_ARTICLE', '删除文章')], max_length=50, verbose_name='操作类型')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败'), ('DENIED', '拒绝')], default='SUCCESS', max_length=20, verbose_name='操作状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详细信息')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_logs', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '权限审计日志',
                'verbose_name_plural': '权限审计日志',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='mdsource_pe_user_id_155bcb_idx'), models.Index(fields=['action', 'timestamp'], name='mdsource_pe_action_f983b6_idx'), models.Index(fields=['status', 'timestamp'], name='mdsource_pe_status_1e7a0c_idx')],
            },
        ),
    ]
